[theme]
primaryColor = "#E8A33D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F5FA"
textColor = "#21295C"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
